REVOKE EXECUTE ON FUNCTION public.admin_approve_signup(uuid, boolean, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_review_topup(uuid, boolean, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_set_moderator_budget(uuid, integer, boolean) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_set_moderator_budget(uuid, integer, boolean, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_set_user_permissions(uuid, public.app_permission[], boolean) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_update_platform_pricing(text, numeric, numeric, numeric) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_update_pricing(integer, integer, integer) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_update_pricing(integer, integer, integer, text, numeric, numeric, numeric) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_update_pricing(integer, integer, integer, text, numeric, numeric, numeric, integer, integer, integer, integer) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_update_user(uuid, integer, boolean, boolean) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.chat_get_or_create_my_conversation(text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.chat_insert_bot_reply(uuid, text, boolean) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.chat_review_credit_request(uuid, boolean, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.chat_send_message(uuid, text, text, integer) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.chat_set_bot_enabled(uuid, boolean, boolean) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_user_tenant(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_permission(uuid, public.app_permission) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_superadmin(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_tenant_admin(uuid, uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_audit(text, text, text, text, jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.push_notification(uuid, text, text, text, text, jsonb) FROM anon, PUBLIC;